config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "flats", to:"flats#index"
  get "flats/new", to: "flats#new"
  post "flats", to: "flats#create"
  get  "flats/:id", to: "flats#show", as: :flats_show
  get "flats/:id/edit", to: "flats#edit", as: :flat_edit
  patch "flats/:id", to: "flats#update"
  delete "flats/:id", to:"flats#destroy", as: :flat_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name iLike '%#{params[:query]}%'")
    else
      @flats = Flat.all
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(flat) do |flat| %>
<%=flat.label :name %>
<%=flat.text_field :name%>
<%=flat.label :address%>
<%=flat.text_field :address%>
<%=flat.label :description%>
<%=flat.text_field :description%>
<%=flat.label :price_per_night%>
<%=flat.text_field :price_per_night%>
<%=flat.label :number_of_guests%>
<%=flat.text_field :number_of_guests%>
<% end %>

app/views/flats/edit.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<h1> All our Flats</h1>
<br>
<br>


<% @flats.each do |flat| %>
    <div class = "appartments-card">
      <h3><%= flat.name %></h3>
      <p><%=flat.description%></p>
      <p><%=flat.address%></p>
      <div class = "appartments-cardbottom">
      <i class="fas fa-user-friends"></i><p><%=flat.number_of_guests%></p><p><%=flat.price_per_night%></p>
      </div>
    </div>
<%= link_to 'More info', flats_show_path(flat) %>


  <% end %>
  </div>


  

app/views/flats/new.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<div class = "appartments_card">

<h2><%= @flat.name %></h2>
<p><%=@flat.description%></p>
<p><%=@flat.address%></p>
<p><%=@flat.number_of_guests%></p>
<p><%=@flat.price_per_night%></p>
<%= link_to 'all flats', flats_path(@flat) %>
<%= link_to 'edit', flat_edit_path(@flat) %>
<%= link_to 'Remove',  flat_destroy_path(@flat), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <div class= "row">
  <div class="col-12">
    <%= yield %>
    </div>
    </div>
    </div>
  </body>

</html>